site_name: GSoC 2024 Weekly Report
repo_url: https://github.com/StarTrooper08/
nav: 
  - 'GSoC 2024' : 'index.md'
  - Reports: 
      - Week 1: 'reports/week_1.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    scheme: default
    primary: white
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: simple/github

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/atharvashirdhankar/
    - icon: fontawesome/brands/github
      link: https://github.com/StarTrooper08

